[build]
  # Directorio que contiene los archivos estáticos (index.html, etc.)
  publish = "/"
  # Directorio donde se encuentran las funciones de Netlify
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"